name: lsds-kafka-lab
services:
  rules:
    build: rules
    ports:
      - "5001:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092
  
  alarms1:
    build: alarms
    ports:
      - "5002:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092
  alarms2:
    build: alarms
    ports:
      - "5003:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092
  alarms3:
    build: alarms
    ports:
      - "5004:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092

networks:
  kafka-cluster_kafka-cluster-network:
    external: true