name: lsds-kafka-lab
services:
  rules:
    build: rules
    ports:
      - "5001:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092
  
  alarms:
    build: alarms
    deploy:
      replicas: 3
    ports:
      - "5002:80"
    networks:
      - kafka-cluster_kafka-cluster-network
    environment:
      BROKER: kafka-1:9092

networks:
  kafka-cluster_kafka-cluster-network:
    external: true