version: "2"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode1:
    image: apache/hadoop:3
    command: >
      sh -c "sudo chown -R hadoop /hadoop-data &&
             hdfs datanode"
    env_file:
      - ./config
    volumes:
      - /hadoop-data
  datanode2:
    image: apache/hadoop:3
    command:  >
      sh -c "sudo chown -R hadoop /hadoop-data &&
             hdfs datanode"
    env_file:
      - ./config
    volumes:
      - /hadoop-data
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
        - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
  testclient:
    image: apache/hadoop:3
    command: ["sleep", "infinity"]
    env_file:
      - ./config